title: blogposts
description: Notes and writeups from my projects
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Haley Gan
