direction: right

# GitHub Boundary (Left Side)
github: GitHub {
  style.fill: "#f9f9f9"

  github_action: GitHub Action {
    shape: rectangle
  }

  github_oidc: OpenID Connect (Github OIDC) {
    shape: rectangle
    style.fill: "#eaeaea"
  }
}

gcp: GCP {
  style.fill: "#f0f4f8"

  gcp_sts: Security Token Service (STS) {
    shape: rectangle
    style.fill: "#689f38"
    style.font-color: "#ffffff"
  }

  wif_config: Workload Identity Pool & Provider {
    label: "Workload Identity Federation Pool - Github Provider"
    shape: rectangle
    style.stroke-dash: 5
  }
}

# Interactions
github.github_action -> github.github_oidc: 1. Request OIDC Token
github.github_oidc -> github.github_action: 2. Return OIDC JWT

github.github_action -> gcp.gcp_sts: 3. Send OIDC JWT to STS
gcp.gcp_sts -> gcp.wif_config: 4. Fetch Attriburte & Mappings and Conditions

gcp.gcp_sts -> gcp.gcp_sts: "6. Access and Evaluate Attribute Conditions)"

gcp.gcp_sts -> github.github_action: 7. Return Federated STS Token
